# This instructs Yarn to fetch packages for both x64 and arm64 CPUs
# on Linux, which is the typical build environment for Konflux.
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux

nodeLinker: node-modules

# Enable Corepack for version management
enableGlobalCache: true
