---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-admin
  namespace: kuadrant-test-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-admin-role
rules:
# full access to all kuadrant policies
- apiGroups:
  - kuadrant.io
  resources:
  - authpolicies
  - dnspolicies
  - ratelimitpolicies
  - tlspolicies
  verbs:
  - '*'
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies
  verbs:
  - '*'
# manage gateways and httproutes
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
# manage configmaps for api key requests
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
# manage secrets for api keys
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
# read namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuadrant-test-api-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-admin-role
subjects:
- kind: ServiceAccount
  name: api-admin
  namespace: kuadrant-test-users
---
# full access to api-requests namespace for approval queue
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-admin-requests
  namespace: api-requests
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: api-admin
  namespace: kuadrant-test-users
