---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: limited-viewer
  namespace: kuadrant-test-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: limited-viewer-role
rules:
# only read authpolicies and ratelimitpolicies
- apiGroups:
  - kuadrant.io
  resources:
  - authpolicies
  - ratelimitpolicies
  verbs:
  - get
  - list
  - watch
# no access to dnspolicies, tlspolicies, or planpolicies
# read namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kuadrant-test-limited-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: limited-viewer-role
subjects:
- kind: ServiceAccount
  name: limited-viewer
  namespace: kuadrant-test-users
