apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: planpolicy-editor
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
