apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: planpolicy-reader
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - extensions.kuadrant.io
  resources:
  - planpolicies
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
  - watch
