name: Build and Push Multi-Arch Image

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

env:
  REGISTRY_USER: ${{ secrets.QUAY_USER }}
  REGISTRY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
  IMAGE_NAME: quay.io/kuadrant/console-plugin

jobs:
  build:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: quay.io

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Push Image by Platform
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-${{ matrix.platform }}

  manifest:
    name: Create and Push Multi-Arch Manifest
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Quay.io
        uses: docker/login-action@v2
        with:
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          registry: quay.io

      - name: Create and Push Multi-Arch Manifest
        run: |
          docker buildx imagetools create \
            --tag ${{ env.IMAGE_NAME }}:latest \
            --tag ${{ env.IMAGE_NAME }}:${{ github.sha }} \
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-linux/amd64 \
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-linux/arm64
